### ISSUE TITLE
Add IDs for scraped members

### ISSUE THREAD

**Issue by chrismytton** [mysociety/argentina-diputados-santa-fe#1]
Looking at http://www.diputadossantafe.gov.ar/web/camara/diputados I think there are 3 possible things we could scrape and use as an ID:

- The email address, e.g. angelinif@diputadossantafe.gov.ar
- The filename of the image, e.g. http://www.diputadossantafe.gov.ar/web/files/Diputados/4/img/angelini-federico.jpg -> `angelini-federico`
- The last part of the "CONCERTAR ENTREVISTA" link path, e.g. http://conferencias.diputadossantafe.gov.ar/#/turnos/calendario/federicoangelini -> `federicoangelini`

**Comment by jacksonj04** [comment]
For any of these things, are they more robust than just hashing the name? presumably they'd all change if the person's name changed anyway

**Comment by chrismytton** [comment]
@jacksonj04 I think for our purposes an email address is probably stable enough to be used as an ID. Hashing the name can cause problems if they fix spelling mistakes, add missing accents, re-order the name etc, which is less likely to happen for an email address.

**Comment by jacksonj04** [comment]
Added in https://github.com/mysociety/argentina-diputados-santa-fe/commit/9e0aba1341d56357a89504b4ae1b78956e7f9c6f, although I make no claims as to its resiliency in the face of even a light breeze.
